In [5]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris

In [2]:
iris = load_iris()
df = pd.DataFrame(iris.data, columns= iris.feature_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [3]:
df['target']= iris.target
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [4]:
df['target'] = df.target.apply(lambda x: iris.target[x])
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [6]:
x = iris.data
y = iris.target 

In [11]:
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score

In [12]:
cross_val_score(SVC(kernel='linear',C=10,gamma='auto'),x,y,cv=5)    

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [13]:
cross_val_score(SVC(kernel='rbf',C=10,gamma='auto'),x,y,cv=5)    

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [14]:
cross_val_score(SVC(kernel='rbf',C=20,gamma='auto'),x,y,cv=5)    

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

In [15]:
from sklearn.model_selection import GridSearchCV

In [17]:
clf = GridSearchCV(SVC(gamma='auto'),{
    'C': [1,10,20,30,100],
    'kernel': ['rbf','linear']
}, cv=5, return_train_score= False)

clf.fit(x,y)
result_SVC= pd.DataFrame(clf.cv_results_)

In [19]:
result_SVC

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.001405  4.990636e-04         0.000899        0.000188       1   
1       0.000777  3.895328e-04         0.000406        0.000497       1   
2       0.000803  4.018041e-04         0.000599        0.000489      10   
3       0.000800  3.998489e-04         0.000000        0.000000      10   
4       0.000800  4.001145e-04         0.000200        0.000399      20   
5       0.000793  3.965987e-04         0.000004        0.000008      20   
6       0.000584  4.780369e-04         0.000400        0.000490      30   
7       0.000800  3.999949e-04         0.000200        0.000400      30   
8       0.001000  6.143617e-07         0.000200        0.000400     100   
9       0.000800  4.002840e-04         0.000200        0.000400     100   

  param_kernel                          params  split0_test_score  \
0          rbf       {'C': 1, 'kernel': 'rbf'}           0.966667   
1       linear    {'C': 1, 'kernel': 'linear'}           0.966667   
2          rbf      {'C': 10, 'kernel': 'rbf'}           0.966667   
3       linear   {'C': 10, 'kernel': 'linear'}           1.000000   
4          rbf      {'C': 20, 'kernel': 'rbf'}           0.966667   
5       linear   {'C': 20, 'kernel': 'linear'}           1.000000   
6          rbf      {'C': 30, 'kernel': 'rbf'}           0.966667   
7       linear   {'C': 30, 'kernel': 'linear'}           1.000000   
8          rbf     {'C': 100, 'kernel': 'rbf'}           1.000000   
9       linear  {'C': 100, 'kernel': 'linear'}           1.000000   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0           1.000000           0.966667           0.966667                1.0   
1           1.000000           0.966667           0.966667                1.0   
2           1.000000           0.966667           0.966667                1.0   
3           1.000000           0.900000           0.966667                1.0   
4           1.000000           0.900000           0.966667                1.0   
5           1.000000           0.900000           0.933333                1.0   
6           1.000000           0.900000           0.933333                1.0   
7           1.000000           0.900000           0.900000                1.0   
8           0.966667           0.900000           0.933333                1.0   
9           1.000000           0.900000           0.933333                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.980000        0.016330                1  
1         0.980000        0.016330                1  
2         0.980000        0.016330                1  
3         0.973333        0.038873                4  
4         0.966667        0.036515                5  
5         0.966667        0.042164                6  
6         0.960000        0.038873                8  
7         0.960000        0.048990                8  
8         0.960000        0.038873                8  
9         0.966667        0.042164                6

In [20]:
clf.best_score_

0.9800000000000001

In [21]:
clf.best_params_

{'C': 1, 'kernel': 'rbf'}

In [44]:
from sklearn.model_selection import RandomizedSearchCV

rs = RandomizedSearchCV(SVC(gamma='auto'),{
    'C': [1,10,20],
    'kernel': ['rbf','linear']
    },
    cv=5,
    return_train_score = False,
    n_iter = 2
)

In [47]:
rs.fit(x,y)
res = pd.DataFrame(rs.cv_results_)[['param_C','param_kernel','mean_test_score']]
res

param_C param_kernel  mean_test_score
0       1       linear         0.980000
1      20       linear         0.966667